---
title: "Appendix C: Additional explorations of deployment"
output:
  html_notebook:
    toc: yes
    toc_depth: 4
    toc_float: yes
always_allow_html: yes
---

```{r global_options, include = F}
knitr::opts_chunk$set(fig.width = 3, fig.asp = 0.67,
                      include = F, echo = F)
```

```{r}
# # for knitting to .docx
# output:
#   word_document:
#     reference_docx: "./word-styles-reference.docx"
# always_allow_html: yes

# # for knitting to .nb.html 
# output:
#   html_notebook:
#     toc: yes
#     toc_depth: 4
#     toc_float: yes
```

```{r}
# run ur-setup script (which runs other scripts)
source("./scripts/_SETUP.R")

# load in EFAs & names from Chapters III & IV
source("./scripts/stored_ch03.R")
source("./scripts/stored_ch04.R")
```

# Appendix overview

In this appendix, XX

```{r}
figure_temp <- scores_all %>%
  filter(!grepl("Study 1", study)) %>%
  # filter(study == "Study 2") %>%
  left_join(d2_79 %>% distinct(subid, age) %>%
              full_join(d3_79 %>% distinct(subid, age)) %>%
              full_join(d3_46 %>% distinct(subid, age)) %>%
              full_join(d4_46 %>% distinct(subid, age)) %>%
              mutate(age_bin = ntile(age, 12))) %>% # could use cut() or ntile()
  left_join(anim_lookup) %>%
  mutate(age_bin = ifelse(is.na(age_bin), "adults",
                          as.character(str_pad(age_bin, 2, pad = "0"))),
         age_group = ifelse(age_bin == "adults", "adults", "children")) %>%
    group_by(study, factor, anim_inan, age_group, age_bin) %>%
  multi_boot_standard(col = "score") %>%
  ggplot(aes(x = age_bin, y = mean, color = anim_inan, size = age_group)) +
  facet_grid(study ~ factor, scales = "free_x", space = "free_x") +
  geom_hline(data = . %>% filter(age_group == "adults"),
             aes(yintercept = mean, color = anim_inan), lty = 2) +
  geom_pointrange(aes(ymin = ci_lower, ymax = ci_upper),
                  position = position_dodge(width = 0.5)) +
  scale_color_manual(values = colorsAI) +
  scale_size_manual(values = c(1, 0.5)) +
  theme(legend.position = "bottom",
        axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1)) +
  labs(x = "Age bin (roughly even cuts between 4-9y)", y = "Mean score")
```

```{r, include = T, fig.width = 6, fig.asp = 0.8}
figure_temp
```

```{r}
table5.7 <- scores_sum %>%
  select(-study) %>%
  rename("BODY vs. HEART" = r_BH, 
         "BODY vs. MIND" = r_BM, 
         "HEART vs. MIND" = r_HM,
         "Animacy status" = anim_inan, 
         "Age group" = age_group) %>%
  rename_at(vars(starts_with("mean_"), starts_with("sd_")),
            funs(gsub("_.*$", "", .))) %>%
  kable(digits = 2,
        caption = "Table 5.7: Summary statistics for BODY, HEART, and MIND scores in Studies 2-4, organized by the age group of participants and the animacy status of target characters.") %>%
  kable_styling() %>%
  column_spec(seq(3, 9, 2), border_left = T) %>%
  collapse_rows(1, valign = "top") %>%
  group_rows("Study 2", 1, 4) %>%
  group_rows("Study 3", 5, 10) %>%
  group_rows("Study 4", 11, 14) %>%
  add_header_above(c(" " = 2, "BODY" = 2, "HEART" = 2, "MIND" = 2,
                     "Correlations (Pearson's r)" = 3))
```

```{r, include = T}
table5.7
```

