---
title: "Dimkid: Topic Modeling (LDA)"
output: html_notebook
---

```{r global_options, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

# Setup

```{r setup, include = F}
# load libraries
library(tidyverse)
library(psych)
library(langcog) # source: https://github.com/langcog/langcog
library(RColorBrewer)
library(plotly)
library(lubridate)
library(rms)
library(topicmodels)
library(tidytext)
```

```{r functions, include = F}
# make rounding function
round2 <- function(x) {format(round(x, 2), nsmall = 2)}

# make cleanup function
cleanup <- function(datasource, age_group) {
  if(grepl("adult", age_group)) {
    
    # set target dataset
    if(datasource == "study 1"){d <- d_raw_study1}
    if(datasource == "study 1b"){d <- d_raw_study1b}
    if(datasource == "study 1c"){d <- d_raw_study1c}
    
    # enact exclusionary criteria
    d_clean_1 <- d
    
    # recode background and demographic variables
    d_clean <- d_clean_1 %>%
      mutate( # deal with study number
        study = factor(study)) %>%
      mutate( # deal with race
        race_cat2 = factor(sub(" +$", "", ethnicity)),
        race_cat3 = factor(ifelse(grepl(" ", race_cat2) == T, "multiracial",
                                  as.character(race_cat2)))) %>%
      dplyr::select(study, subid:country_selfrep, age_group, race_cat3) %>%
      rename(race_cat = race_cat3) %>%
      mutate( # deal with religion (note: only dealing with childhood religion for now)
        religion_cat2 = factor(sub(" +$", "", religionChild)),
        religion_cat3 = factor(ifelse(grepl(" ", religion_cat2) == T, 
                                      "multireligious",
                                      as.character(religion_cat2)))) %>%
      dplyr::select(study:race_cat, religion_cat3) %>%
      rename(religion_cat = religion_cat3)
    
    # remove extraneous dfs and variables
    rm(d, d_clean_1)
  }
  
  if(grepl("child", age_group)) {
    
    # set target dataset
    if(datasource == "study 2"){d <- d_raw_study2}
    if(datasource == "study 3"){d <- d_raw_study3}
    if(datasource == "study 4"){d <- d_raw_study4}
    if(datasource == "study 5"){d <- d_raw_study5}
    
    # recode background and demographic variables
    d_clean_2 <- d %>%
      mutate( # deal with study number
        study = factor(study),
        responseNum = ifelse(!is.na(responseNum), responseNum,
                             ifelse(response == "no", 0, 
                                    ifelse(response == "kinda", 0.5, 
                                           ifelse(response == "yes", 1, NA)))))
    # NOTE: need to reconcile race/ethnicity at some point...
    # NOTE: need to deal with gender at some point...
  
    d_clean <- d_clean_2
    
    # remove extraneous dfs and variables
    rm(d, d_clean_2)
  }
  
  # remove outliers if desired
  if(chosenOutlierHandling == "remove") {
    
    d_clean <- d_clean %>%
      gather(capacity, score, happy:pride) %>%
      group_by(character, capacity) %>%
      filter(!score %in% boxplot.stats(score, 2.5)$out) %>%
      spread(capacity, score) %>%
      arrange(character, subid)
    
  }
  
  # filter characters if desired
  if(is.element("none", chosenExclude)) {} else {
    
    d_clean <- d_clean %>%
      filter(!character %in% chosenExclude)
    
    }
    
  # filter items if desired
  if(is.element("none", chosenExcludeItem)) {} else {
    d_clean <- d_clean %>%
      dplyr::filter(!capacity %in% chosenExcludeItem)
  }
  
  # drop trials <250 ms
  d_clean <- d_clean %>%
    filter(rt >= 250 | is.na(rt))
  
  # center response variable
  if(datasource == "study 1b") {
    d_clean <- d_clean %>%
      mutate(responseNumC = responseNum - 4)
  } else {
    d_clean <- d_clean %>%
      mutate(responseNumC = responseNum - 0.5)
  }

    # rename character name variables
  if("charName" %in% names(d_clean)) {
    d_clean <- d_clean %>% rename(character = charName)
  }
  
  # cleanup
  d_clean <- d_clean %>%
    filter(!is.na(subid), !is.na(character), !is.na(capacity))
  
  # return cleaned dataset
  return(d_clean)
}

# make function for stripping dataframes for dimension reducation
makeDRDF <- function(datasource, chosenCondition) {
  
  # set target dataset
  if(datasource == "study 1"){d <- d1}
  if(datasource == "study 1b"){d <- d1b}
  if(datasource == "study 1c"){d <- d1c}
  if(datasource == "study 2"){d <- d2}
  if(datasource == "study 3"){d <- d3}
  if(datasource == "study 4"){d <- d4}
  if(datasource == "study 5"){d <- d5}

  # filter by character if specified
  if(chosenCondition %in% c("beetle", "robot")) {
    d <- d %>% filter(character == chosenCondition)
  }

  # make stripped dataframe for dimension reducation analyses
  d_strip <- d %>%
    filter(!is.na(character), !is.na(subid), !is.na(capacity), capacity != "") %>%
    mutate(subid = paste(character, subid, sep = "_")) %>%
    select(subid, capacity, responseNum) %>%
    spread(capacity, responseNum) %>%
    remove_rownames() %>%
    column_to_rownames(var = "subid")

  # return stripped dataframe
  return(d_strip)
}

# make demographics functions
demoSampleSize <- function(datasource) {

  # set target dataset
  if(datasource == "study 1"){d <- d1}
  if(datasource == "study 1b"){d <- d1b}
  if(datasource == "study 1c"){d <- d1c}
  if(datasource == "study 2"){d <- d2}
  if(datasource == "study 3"){d <- d3}
  if(datasource == "study 4"){d <- d4}
  if(datasource == "study 5"){d <- d5}

  # get distinct subids
  sample_size <- d %>% distinct(subid, character) %>% count(character) %>% data.frame()

  # add total sample size  
  sample_size <- rbind(sample_size %>% mutate(character = as.character(character)),
                       c(character = "all", n = d %>% distinct(subid) %>% count() %>% as.numeric()))
  
  # return dataframe
  return(sample_size)
}
demoDuration <- function(datasource) {

  # set target dataset
  if(datasource == "study 1"){d <- d1}
  if(datasource == "study 1b"){d <- d1b}
  if(datasource == "study 1c"){d <- d1c}
  if(datasource == "study 2"){d <- d2}
  if(datasource == "study 3"){d <- d3}
  if(datasource == "study 4"){d <- d4}
  if(datasource == "study 5"){d <- d5}

  # get sample size per character
  duration <- d %>%
    distinct(subid, character, duration) %>%
    mutate(duration = as.numeric(duration)) %>%
    group_by(character) %>%
    summarise(min_duration = min(duration, na.rm = T),
              max_duration = max(duration, na.rm = T),
              median_duration = median(duration, na.rm = T),
              mean_duration = mean(duration, na.rm = T),
              sd_duration = sd(duration, na.rm = T))

  # add total duration
  all <- d %>%
    distinct(subid, character, duration) %>%
    mutate(duration = as.numeric(duration)) %>%
    summarise(min_duration = min(duration, na.rm = T),
              max_duration = max(duration, na.rm = T),
              median_duration = median(duration, na.rm = T),
              mean_duration = mean(duration, na.rm = T),
              sd_duration = sd(duration, na.rm = T)) %>%
    mutate(character = "all")
  
  duration <- rbind(duration, all) # not sure why full_join doesn't work    

  # return dataframe
  return(duration)
}
demoAge <- function(datasource) {

  # set target dataset
  if(datasource == "study 1"){d <- d1}
  if(datasource == "study 1b"){d <- d1b}
  if(datasource == "study 1c"){d <- d1c}
  if(datasource == "study 2"){d <- d2}
  if(datasource == "study 3"){d <- d3}
  if(datasource == "study 4"){d <- d4}
  if(datasource == "study 5"){d <- d5}

  # get sample size per character
  age <- d %>%
    distinct(subid, character, age) %>%
    mutate(age = as.numeric(age)) %>%
    group_by(character) %>%
    summarise(min_age = min(age, na.rm = T),
              max_age = max(age, na.rm = T),
              median_age = median(age, na.rm = T),
              mean_age = mean(age, na.rm = T),
              sd_age = sd(age, na.rm = T))

  # add total age
  all <- d %>%
    distinct(subid, character, age) %>%
    mutate(age = as.numeric(age)) %>%
    summarise(min_age = min(age, na.rm = T),
              max_age = max(age, na.rm = T),
              median_age = median(age, na.rm = T),
              mean_age = mean(age, na.rm = T),
              sd_age = sd(age, na.rm = T)) %>%
    mutate(character = "all")
  age <- full_join(age, all)

  # return dataframe
  return(age)
}
demoGender <- function(datasource) {

  # set target dataset
  if(datasource == "study 1"){d <- d1}
  if(datasource == "study 1b"){d <- d1b}
  if(datasource == "study 1c"){d <- d1c}
  if(datasource == "study 2"){d <- d2}
  if(datasource == "study 3"){d <- d3}
  if(datasource == "study 4"){d <- d4}
  if(datasource == "study 5"){d <- d5}

  # get gender per character and overall
  gender <- data.frame(addmargins(with(d %>% distinct(subid, character, gender), 
                                       table(character, gender)))) %>%
    filter(gender != "Sum") %>%
    rename(n = Freq)
  
  gender <- gender %>%
    mutate(character = factor(ifelse(character == "Sum",
                                     "all", as.character(character)),
                              levels = c("beetle", "robot", "all"))) %>%
    arrange(character, gender) %>%
    spread(gender, n)
  
  # return dataframe
  return(gender)
}
demoRace <- function(datasource) {

  # set target dataset
  if(datasource == "study 1"){d <- d1}
  if(datasource == "study 1b"){d <- d1b}
  if(datasource == "study 1c"){d <- d1c}
  if(datasource == "study 2"){d <- d2}
  if(datasource == "study 3"){d <- d3}
  if(datasource == "study 4"){d <- d4}
  if(datasource == "study 5"){d <- d5}

  # get race per character and overall
  race <- data.frame(addmargins(with(d %>% distinct(subid, character, race_cat), 
                                     table(character, race_cat)))) %>%
    filter(race_cat != "Sum") %>%
    rename(n = Freq)

    race <- race %>%
      mutate(character = factor(ifelse(character == "Sum",
                                       "all", as.character(character)))) %>%
      arrange(character, race_cat) %>%
      spread(race_cat, n)
  
  # return dataframe
  return(race)
}

# plotting functions
makeFacetLabs <- function(df_plotting) {
  facet_labels <- array()
  df_plotting <- df_plotting %>% mutate(character = factor(character))
  for(i in 1:length(levels(df_plotting$character))) {
    df <- df_plotting %>% filter(character == levels(df_plotting$character)[i]) %>%
      select(character, n) %>% unique()
    facet_labels[i] <- paste0(df$character, " (n = ", df$n, ")")
  }
  names(facet_labels) <- levels(df_plotting$character)
  return(facet_labels)
}
```

```{r modeling decisions, include = F}
# remove outliers?
chosenOutlierHandling <- "keep"
# chosenOutlierHandling <- "remove"

# exclude any conditions (characters)?
chosenExclude <- "none"
# chosenExclude <- c("stapler", "car", "computer")

# exclude any items (mental capacities)?
# chosenExcludeItem <- "none"
# chosenExcludeItem <- "computations"
chosenExcludeItem <- c("metal", "on_off")

# NOTE: always choose minimal residual (fm = "minres") instead of ML because of non-normality

# for EFAs, what kind of correlation?
chosenCorType <- "cor" # pearson correlation
# chosenCorType <- "poly" # polychoric correlation

# for EFAs, what kind of rotation?
# chosenRotType <- "varimax" # varimax rotation
chosenRotType <- "oblimin" # oblimin rotation
# chosenRotType <- "none" # no rotation

data.frame("conditionsExcluded" = chosenExclude,
           "outlierHandling" = chosenOutlierHandling,
           "EFA_correlation" = chosenCorType,
           "EFA_rotation" = chosenRotType)
```

# Data preparation

```{r data upload, include = F}
# study 1 (2016-07-06, adults, 2 conditions, 3-point scale, "decide what to do" and "make plans")
d_raw_study1 <- read.csv("/Users/kweisman/Documents/Research (Stanford)/Projects/Dimkid/dimkid/data/adults/us_run-01_2016-06-05_anonymized.csv") %>%
  mutate(study = "study 1", age_group = "adults") %>% select(-X)

# study 1b (2017-07-19, adults, 2 conditions, 7-point scale, "decide what to do" and "make plans")
d_raw_study1b <- read.csv("/Users/kweisman/Documents/Research (Stanford)/Projects/Dimkid/dimkid/data/adults/us_run-02_2016-07-19_anonymized.csv") %>%
  mutate(study = "study 1b", age_group = "adults") %>% select(-X)

# study 1c (2016-12-08, adults, 2 conditions, 3-point scale, "have free will" and "have intentions")
d_raw_study1c <- read.csv("/Users/kweisman/Documents/Research (Stanford)/Projects/Dimkid/dimkid/data/adults/us_run-03_2016-12-08_anonymized.csv") %>%
  mutate(study = "study 1c", age_group = "adults") %>% select(-X)

# study 2 (June - December 2016, 7-9yo, 2 conditions, 3-point-scale, "decide what to do" and "make plans")
d_raw_study2 <- read.csv("/Users/kweisman/Documents/Research (Stanford)/Projects/Dimkid/dimkid/data/children/run-01_2017-07-24_anonymized.csv") %>%
  mutate(study = "study 2", age_group = "children_79") %>% select(-X)

# study 3 (January - June 2017, 7-9yo, 9 conditions, 3-point-scale, "decide what to do" and "make plans")
d_raw_study3 <- read.csv("/Users/kweisman/Documents/Research (Stanford)/Projects/Dimkid/dimkid/data/children/run-02_2017-08-08_anonymized.csv") %>%
  mutate(study = "study 3", age_group = "children_79") %>% select(-X) %>%
  mutate(dob = parse_datetime(dateOfBirth, "%m/%d/%y"),
         dot = parse_datetime(gsub("2017", "17", dateOfTest), "%m/%d/%y"), 
         age = interval(start = dob, end = dot) / duration(num = 1, units = "years")) %>%
  select(-dateOfBirth, -dateOfTest, -dob, -dot)

# study 4 (May 2017 - present, 4-6yo, 9 conditions, 3-point-scale, "decide what to do" and "make plans")
d_raw_study4 <- read.csv("/Users/kweisman/Documents/Research (Stanford)/Projects/Dimkid/dimkid/data/children/run-03_2017-08-21_anonymized.csv") %>%
  mutate(study = "study 4", age_group = "children_46") %>% select(-X) %>%
  mutate(dob = parse_datetime(dateOfBirth, "%m/%d/%y"),
         dot = parse_datetime(gsub("2017", "17", dateOfTest), "%m/%d/%y"), 
         age = interval(start = dob, end = dot) / duration(num = 1, units = "years")) %>%
  select(-dateOfBirth, -dateOfTest, -dob, -dot)

# study 5 (Fall 2017 - present, 5.5-7.5yo (plus), 9 conditions, 3-point-scale, "decide what to do" and "make plans")
d_raw_study5 <- read.csv("/Users/kweisman/Documents/Research (Stanford)/Projects/Dimkid/dimkid/data/children/run-04_2017-10-10_anonymized.csv") %>%
  mutate(study = "study 5", age_group = "children_5.57.5") %>% select(-X) %>%
  mutate(dob = parse_datetime(dateOfBirth, "%m/%d/%y"),
         dot = parse_datetime(gsub("2017", "17", dateOfTest), "%m/%d/%y"), 
         age = interval(start = dob, end = dot) / duration(num = 1, units = "years")) %>%
  select(-dateOfBirth, -dateOfTest, -dob, -dot)
```

```{r data cleanup, include = F}
# clean up datasets
d1 <- cleanup("study 1", "adults")
d1b <- cleanup("study 1", "adults")
d1c <- cleanup("study 1", "adults")
d2 <- cleanup("study 2", "children")
d3 <- cleanup("study 3", "children")
d4 <- cleanup("study 4", "children")
d5 <- cleanup("study 5", "children")

# tweak by hand
d2 <- d2 %>%
  filter(!is.na(age)) %>%
  filter(age >= 7, age < 10) %>%
  filter(character != "elephant")

d3_outsideage <- d3 %>% filter(age < 7 | age >= 10) %>% distinct(subid)

d3 <- d3 %>%
  filter(!is.na(character), character != "") %>%
  filter(!subid %in% d3_outsideage$subid) %>%
  # filter(age >= 7, age < 10) %>%
  mutate(ethnicity = gsub(" SN", "", ethnicity)) %>%
  mutate(race_cat = ifelse(grepl("bing", tolower(testingSite)),
                           ifelse(ethnicity == "A", "east_asian",
                                  ifelse(ethnicity == "C" | ethnicity == "Cj", "white",
                                         ifelse(ethnicity == "I", "south_asian",
                                                ifelse(ethnicity == "ME", "middle_eastern",
                                                       ifelse(ethnicity == "Af", "black",
                                                              ifelse(ethnicity == "H", "hispanic",
                                                                     ifelse(grepl(" ", ethnicity) |
                                                                              grepl("/", ethnicity), "multiracial",
                                                                            NA))))))),
                           ifelse(tolower(ethnicity) == "black or african american", "black",
                                  ifelse(tolower(ethnicity) == "hispanic or latino/a", "hispanic",
                                         ifelse(tolower(ethnicity) == "east asian", "east_asian",
                                                ifelse(tolower(ethnicity) == "native american, american indian, or alaska native", "native_american",
                                                       ifelse(tolower(ethnicity) == "white" |
                                                                tolower(ethnicity) == "white, caucasian, or european american", "white",
                                                              ifelse(tolower(ethnicity) == "south or southeast asian" | tolower(ethnicity) == "south asian", "south_asian",
                                                                     ifelse(tolower(ethnicity) == "" | is.na(ethnicity), NA, "multiracial")))))))))

d4 <- d4 %>%
  filter(!is.na(character), character != "") %>%
  filter(age >= 4, age < 7) %>%
  mutate(ethnicity = gsub(" SN", "", ethnicity)) %>%
  mutate(race_cat = ifelse(grepl("bing", tolower(testingSite)),
                           ifelse(ethnicity == "A", "east_asian",
                                  ifelse(ethnicity == "C" | ethnicity == "Cj", "white",
                                         ifelse(ethnicity == "I", "south_asian",
                                                ifelse(ethnicity == "ME", "middle_eastern",
                                                       ifelse(ethnicity == "Af", "black",
                                                              ifelse(ethnicity == "H", "hispanic",
                                                                     ifelse(grepl(" ", ethnicity) |
                                                                              grepl("/", ethnicity), "multiracial",
                                                                            NA))))))),
                           ifelse(tolower(ethnicity) == "black or african american", "black",
                                  ifelse(tolower(ethnicity) == "hispanic or latino/a", "hispanic",
                                         ifelse(tolower(ethnicity) == "east asian", "east_asian",
                                                ifelse(tolower(ethnicity) == "native american, american indian, or alaska native", "native_american",
                                                       ifelse(tolower(ethnicity) == "white" |
                                                                tolower(ethnicity) == "white, caucasian, or european american", "white",
                                                              ifelse(tolower(ethnicity) == "south or southeast asian" | tolower(ethnicity) == "south asian", "south_asian",
                                                                     ifelse(tolower(ethnicity) == "" | is.na(ethnicity), NA, "multiracial")))))))))

d5 <- d5 %>%
  filter(!is.na(character), character != "") %>%
  filter(age >= 5.5, age < 7.5) %>%
  mutate(ethnicity = gsub(" SN", "", ethnicity)) %>%
  mutate(race_cat = ifelse(grepl("bing", tolower(testingSite)),
                           ifelse(ethnicity == "A", "east_asian",
                                  ifelse(ethnicity == "C" | ethnicity == "Cj", "white",
                                         ifelse(ethnicity == "I", "south_asian",
                                                ifelse(ethnicity == "ME", "middle_eastern",
                                                       ifelse(ethnicity == "Af", "black",
                                                              ifelse(ethnicity == "H", "hispanic",
                                                                     ifelse(grepl(" ", ethnicity) |
                                                                              grepl("/", ethnicity), "multiracial",
                                                                            NA))))))),
                           ifelse(tolower(ethnicity) == "black or african american", "black",
                                  ifelse(tolower(ethnicity) == "hispanic or latino/a", "hispanic",
                                         ifelse(tolower(ethnicity) == "east asian", "east_asian",
                                                ifelse(tolower(ethnicity) == "native american, american indian, or alaska native", "native_american",
                                                       ifelse(tolower(ethnicity) == "white" |
                                                                tolower(ethnicity) == "white, caucasian, or european american", "white",
                                                              ifelse(tolower(ethnicity) == "south or southeast asian" | tolower(ethnicity) == "south asian", "south_asian",
                                                                     ifelse(tolower(ethnicity) == "" | is.na(ethnicity), NA, "multiracial")))))))))
```

```{r dataframes for dimension reducation, include = F}
# make dataframes for s1
# d1_beetle <- makeDRDF("study 1", "beetle")
# d1_robot <- makeDRDF("study 1", "robot")
d1_all <- makeDRDF("study 1", "all")

# make dataframes for follow-up studies to s1
d1b_all <- makeDRDF("study 1b", "all")
d1c_all <- makeDRDF("study 1c", "all")

# make dataframes for study 2
# d2_beetle <- makeDRDF("study 2", "beetle")
# d2_robot <- makeDRDF("study 2", "robot")
d2_all <- makeDRDF("study 2", "all")

# make dataframes for study 3
# d3_beetle <- makeDRDF("study 3", "beetle")
# d3_robot <- makeDRDF("study 3", "robot")
d3_all <- makeDRDF("study 3", "all")

# make dataframes for study 4
d4_all <- makeDRDF("study 4", "all")
```

```{r dataframe for sliding window, include = F}
# merge datasets from studies 3-4 and run 04
d_slide <- d3 %>%
  select(-trial.comments) %>%
  full_join(d4 %>% select(-trial.comments)) %>%
  full_join(d5 %>% select(-trial.comments)) %>%
  mutate(capacity = recode(capacity,
                           angry = "anger",
                           choices = "choice",
                           conscious = "awareness",
                           depressed = "sadness",
                           depth = "depth",
                           disrespected = "hurt feelings",
                           embarrassed = "embarrassment",
                           fear = "fear",
                           guilt = "guilt",
                           happy = "happiness",
                           hungry = "hunger",
                           love = "love",
                           nauseated = "nausea",
                           odors = "smell",
                           pain = "pain",
                           pride = "pride",
                           reasoning = "figuring out",
                           remembering = "memory",
                           temperature = "temperature",
                           tired = "fatigue"))

# get age ranks
d_slide_subid <- d_slide %>%
  distinct(subid, age) %>%
  arrange(age, subid) %>%
  rownames_to_column("age_rank") %>%
  mutate(age_rank = as.numeric(age_rank))

d_slide <- d_slide %>%
  filter(subid %in% d_slide_subid$subid) %>%
  left_join(d_slide_subid) %>%
  arrange(age_rank, trialNum) %>%
  filter(!is.na(age))

# make wideframe df
d_slide_all <- d_slide %>%
  select(subid, age, character, capacity, responseNum) %>%
  mutate(age = as.numeric(as.character(age))) %>%
  spread(capacity, responseNum) %>%
  arrange(age) %>%
  remove_rownames() %>%
  column_to_rownames("subid")

# limit to complete cases for tsne
d_slide_all_complete <- d_slide_all[complete.cases(d_slide_all),]
```

# Topic modeling

## Adults, 7-point scale

```{r}
# make wideframe df
d1b_prep <- d1b %>%
  select(subid, age, character, capacity, responseNum) %>%
  mutate(age = as.numeric(as.character(age))) %>%
  spread(capacity, responseNum) %>%
  arrange(age) %>%
  remove_rownames() %>%
  column_to_rownames("subid")

# limit to complete cases for tsne
d1b_all_complete <- d1b_prep[complete.cases(d1b_prep),]

# make LDA-friendly df
d1b_LDA <- d1b_all_complete %>%
  rownames_to_column("subid") %>%
  select(-age, -character) %>%
  gather(capacity, response, -subid) %>%
  mutate(response = ifelse(response > 0, 1, response)) # legit?
  # mutate(response = (response * 2)) # is this legit? not counts...

d1b_LDA_keep <- d1b_LDA %>%
  ungroup() %>%
  group_by(subid) %>%
  summarise(sum = sum(response, na.rm = T)) %>%
  filter(sum != 0) %>%
  mutate(subid = as.character(subid))
  
d1b_LDA <- d1b_LDA %>%
  filter(subid %in% d1b_LDA_keep$subid) %>%
  ungroup() %>%
  spread(capacity, response) %>%
  remove_rownames() %>%
  column_to_rownames("subid")

# do LDA
d1b_LDA <- LDA(x = d1b_LDA, k = 10)
```

```{r}
# look at terms by topic
d1b_LDA_topics <- tidy(d1b_LDA, matrix = "beta")

d1b_LDA_termorder <- d1b_LDA_topics %>%
  group_by(term) %>%
  top_n(1, beta) %>%
  arrange(topic, desc(beta)) %>%
  data.frame() %>%
  rownames_to_column("order") %>%
  mutate(order = as.numeric(as.character(order)))

ggplot(d1b_LDA_topics %>%
         full_join(d1b_LDA_termorder %>% select(term, order)) %>%
         distinct(),
       aes(x = topic, y = reorder(term, desc(order)), fill = beta)) +
  geom_tile() +
  scale_fill_distiller(palette = "YlGn", direction = 1,
                       guide = guide_colorbar(title = element_blank(),
                                              barheight = 10)) +
  theme_minimal()
```

```{r, fig.width = 4, fig.height = 2}
# look at topics by "document" (participant)
d1b_LDA_documents <- tidy(d1b_LDA, matrix = "gamma") %>%
  rename(subid = document)

d1b_LDA_docorder <- d1b_LDA_documents %>%
  group_by(subid) %>%
  top_n(1, gamma) %>%
  arrange(topic, desc(gamma)) %>%
  data.frame() %>%
  rownames_to_column("order") %>%
  mutate(order = as.numeric(as.character(order))) %>%
  full_join(d1b_all_complete %>% 
              rownames_to_column("subid") %>% 
              select(subid, age, character))

# ggplot(d1b_LDA_documents %>%
#          full_join(d1b_LDA_docorder %>% select(subid, order)),
#        aes(x = topic, y = reorder(subid, desc(order)), fill = gamma)) +
#   geom_tile() +
#   scale_fill_distiller(palette = "RdYlBu", 
#                        guide = guide_colorbar(title = element_blank(),
#                                               barheight = 10)) +
#   theme_minimal()

ggplot(d1b_LDA_documents %>% 
         full_join(d1b_LDA_docorder) %>% 
         filter(!is.na(character), !is.na(topic)) %>%
         distinct(),
       aes(x = age, y = gamma, color = factor(topic))) +
  # facet_wrap(~ topic) +
  facet_grid(character ~ topic) +
  geom_point() +
  # geom_smooth(method = "lm") +
  theme_bw()
```



## 4-10yo

```{r}
# make LDA-friendly df
d_slide_LDA <- d_slide_all_complete %>%
  rownames_to_column("subid") %>%
  select(-age, -character) %>%
  gather(capacity, response, -subid) %>%
  mutate(response = ifelse(response > 0, 1, response)) # legit?
  # mutate(response = (response * 2)) # is this legit? not counts...

d_slide_LDA_keep <- d_slide_LDA %>%
  ungroup() %>%
  group_by(subid) %>%
  summarise(sum = sum(response, na.rm = T)) %>%
  filter(sum != 0) %>%
  mutate(subid = as.character(subid))
  
d_slide_LDA <- d_slide_LDA %>%
  filter(subid %in% d_slide_LDA_keep$subid) %>%
  ungroup() %>%
  spread(capacity, response) %>%
  remove_rownames() %>%
  column_to_rownames("subid")

# do LDA
d_slide_LDA <- LDA(x = d_slide_LDA, k = 3)
```

```{r}
# look at terms by topic
d_slide_LDA_topics <- tidy(d_slide_LDA, matrix = "beta")

d_slide_LDA_termorder <- d_slide_LDA_topics %>%
  group_by(term) %>%
  top_n(1, beta) %>%
  arrange(topic, desc(beta)) %>%
  data.frame() %>%
  rownames_to_column("order") %>%
  mutate(order = as.numeric(as.character(order)))

ggplot(d_slide_LDA_topics %>%
         full_join(d_slide_LDA_termorder %>% select(term, order)) %>%
         distinct(),
       aes(x = topic, y = reorder(term, desc(order)), fill = beta)) +
  geom_tile() +
  scale_fill_distiller(palette = "YlGn", direction = 1,
                       guide = guide_colorbar(title = element_blank(),
                                              barheight = 10)) +
  scale_x_continuous(breaks = 1:10) +
  theme_minimal()
```

```{r, fig.width = 4, fig.height = 6}
# look at topics by "document" (participant)
d_slide_LDA_documents <- tidy(d_slide_LDA, matrix = "gamma") %>%
  rename(subid = document)

d_slide_LDA_docorder <- d_slide_LDA_documents %>%
  group_by(subid) %>%
  top_n(1, gamma) %>%
  arrange(topic, desc(gamma)) %>%
  data.frame() %>%
  rownames_to_column("order") %>%
  mutate(order = as.numeric(as.character(order))) %>%
  full_join(d_slide_all_complete %>% 
              rownames_to_column("subid") %>% 
              select(subid, age, character))

# ggplot(d_slide_LDA_documents %>%
#          full_join(d_slide_LDA_docorder %>% select(subid, order)),
#        aes(x = topic, y = reorder(subid, desc(order)), fill = gamma)) +
#   geom_tile() +
#   scale_fill_distiller(palette = "RdYlBu", 
#                        guide = guide_colorbar(title = element_blank(),
#                                               barheight = 10)) +
#   theme_minimal()

ggplot(d_slide_LDA_documents %>% 
         full_join(d_slide_LDA_docorder %>% select(subid, character, age)) %>% 
         filter(!is.na(character), !is.na(topic)) %>%
         distinct(),
       aes(x = age, y = gamma, 
           # color = character, fill = character)) +
           color = factor(topic), fill = factor(topic))) +
  # facet_grid(~ topic) +
  facet_grid(character ~ topic) +
  geom_point() +
  geom_smooth(method = "lm") +
  theme_bw()
```

```{r}
library(plotly)
plot_ly(d_slide_LDA_documents %>%
          mutate(topic = recode(topic,
                                "1" = "topic_1",
                                "2" = "topic_2",
                                "3" = "topic_3")) %>%
          spread(topic, gamma) %>%
          full_join(d_slide_LDA_docorder %>% 
                      select(subid, age, character)) %>%
          filter(!is.na(character)),
        x = ~topic_1, y = ~topic_2, z = ~topic_3,
        color = ~age,
        # color = ~character,
        # size = ~age,
        opacity = 0.6)
```

